# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
parameters:
- name: build
  type: string
  default: null
  values: 
  - 1
  - 2

name: sample
trigger:
- master
- dev

pool: sample

variables:
- group : 

stages:
- stage: build 
  jobs:
  - job: gatheringdepen
    steps:
    - task: Maven@4
      displayName: build using maven
      inputs:
        mavenPomFile: 'pom.xml'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        javaHomeOption: 'JDKVersion'
        mavenVersionOption: 'Default'
        mavenAuthenticateFeed: false
        effectivePomSkip: false
        sonarQubeRunAnalysis: false
    - task: Bash@3
      inputs:
        filePath: '/home/'
    - script: |
       echo $(branch)
       