name : sample

parameters:
- name: 
  type: string
  default: null
  values:
  - one
  - two

trigger:
- master

pool: 
 vm_image: ubuntu-latest

stages:
- stage: printing_parameters
  jobs:
  - job: print
    steps:
    - task: Bash@3
      displayName: bashtask
      inputs:
        targetType: 'inline'
        script: |          
          echo "Hello world"
          echo "build number: ${{buildnumber}}
    